


# Services or Containers List definition
services:
  db:
    image: mysql:latest
    container_name: mysql-capstone-server
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql # Mount directory settings (-v option)
    environment:
      - MYSQL_ROOT_PASSWORD=capstone
      - MYSQL_DATABASE=capstone-server
      - MYSQL_USER=capstone_user_server
      - MYSQL_PASSWORD=capstonePassword
      - TZ=Asia/Seoul
    command: # Command execution
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis_container:
    image: redis
    container_name: redis-capstone-server
    ports:
      - 6379:6379
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 8080:8080
